name: test

on: push

jobs:
  publish-pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.7
          uses: actions/setup-python@v1
          with:
            python-version: 3.7
      - name: Install twine
        run: |
          python3 -m pip install --user --upgrade setuptools wheel
          python3 -m pip install --user --upgrade twine
      - name: Generating distribution archives
        run: |
          python3 setup.py sdist bdist_wheel
      - name: Publish distribution 📦 to PyPI
          if: startsWith(github.event.ref, 'refs/tags')
          uses: pypa/gh-action-pypi-publish@master
          with:
            password: ${{ secrets.pypi_password }}
